# Generated by Django 5.0.1 on 2024-01-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=200)),
                ('winner', models.CharField(max_length=200)),
            ],
        ),
    ]
